### ISSUE TITLE
User can get solution to a math problem.

### ISSUE THREAD

**Issue by alexdenbaugh** [alexdenbaugh/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can get solution to a math problem

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able chose a math topic and submit a math problem that will return the solution.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature one screen shot](https://user-images.githubusercontent.com/78943990/114757267-7ac99180-9d10-11eb-8516-a6d9de9d30b7.PNG)
![Feature one screen shot desktop](https://user-images.githubusercontent.com/78943990/114757274-7c935500-9d10-11eb-99e8-3f1903639f76.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create header
- [x] Create homepage
- [x] Make anchor tag for application title that returns to home page
- [x] Set up css for mobile and desktop with `@media`
- [x] Create 'Calculator' window
- [x] Make Calculator form
- [x] Make data model in JS
- [x] Set up API `XMLHTTPRequest` in JS
- [x] Encode necessary characters to UTF-8.
- [x] Make some dummy data that tests each problem type.
- [x] Create form event listener for `submit` event.
- [x] Create guards for incorrect inputs
- [x] Make error prompt when problem isn't submitted correctly.
- [x] Manipulate form entries' inputs when necessary (logarithms, trig). 
- [x] Don't refresh form when problem is inputted.
- [x] Update "result" window with solution or error when form is submitted.
- [x] Make hamburger menu with anchor tags that change between calculator, home page, progress, and practice windows.
- [x] make transitions/transforms/pseudo classes for buttons and anchors.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
