### ISSUE TITLE
User can view randomly generated math problems

### ISSUE THREAD

**Issue by alexdenbaugh** [alexdenbaugh/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view randomly generated math problems
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view a randomly generated problem in practice mode

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature two screen shot mobile](https://user-images.githubusercontent.com/78943990/114765766-65f1fb80-9d1a-11eb-9a50-2dd23e07add7.PNG)
![Feature two screen shot desktop](https://user-images.githubusercontent.com/78943990/114765818-7c985280-9d1a-11eb-81d0-7880bde42329.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create "Practice" view and give it `data-view="practice"`
- [x] Style with css
- [x] Check to see if view's can change properly.
- [x] Change necessary text content based on the problem and problem type.
- [x] Toggle the "denominator `h1`  with the hidden class when necessary.
- [x] Create Polynomial generator
- [x] Create problem generator for simplification.
- [x] Create problem generator for factoring.
- [x] Create problem generator for derivation.
- [x] Create problem generator for integration.
- [x] Change '^' to `<sup>` elements.
- [x] Update DOM with newly generated problem.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
