### ISSUE TITLE
User can choose problem type

### ISSUE THREAD

**Issue by alexdenbaugh** [alexdenbaugh/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can choose problem type
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can choose one or all problem types between 'Simplification', 'Factoring', 'Derivation', and 'Integration'.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature three screen shot mobile](https://user-images.githubusercontent.com/78943990/114766269-09dba700-9d1b-11eb-9bf2-8f996e021c2d.PNG)
![Feature three screen shot desktop](https://user-images.githubusercontent.com/78943990/114766277-0b0cd400-9d1b-11eb-8518-ed0d362a1079.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a practice-settings `data-view` in html
- [x] Create a `<form>` for the problem types.
- [x] Check one option when the form is refreshed.
- [x] Style in CSS
- [x] Add practice-settings `data-view` option in view changer function
- [x] Link practice option in hamburger menu to practice-settings `data-view`
- [x] Add an `addEventListener` to the `form`.
- [x] Link Start `<button>` to practice problem view.
- [x] Call `practiceProblem()` when Start `<button>` clicked.
- [x] Filter out problem types based on `form` inputs.
- [x] Show error prompt if no settings were selected, hide error prompt when start button is clicked.
- [x] When switching to and from practice, make sure practice-settings view is showing when practice `<button>`'s are clicked.
- [x] Don't reset practice-settings `<form>` after leaving page or when going back to page. (User might want to practice same problems over and over.)
- [x] Fix bug that shows the answer of the question in practice in calculator view.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
