### ISSUE TITLE
User can practice solving randomly generated problems.

### ISSUE THREAD

**Issue by alexdenbaugh** [alexdenbaugh/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can practice solving randomly generated problems.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can input a response to the given problem and get a response of correct or incorrect.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature four screen shot mobile](https://user-images.githubusercontent.com/78943990/114766871-ccc3e480-9d1b-11eb-954e-0eaca7bd0e10.PNG)
![Feature four screen shot desktop](https://user-images.githubusercontent.com/78943990/114766724-9a19ec00-9d1b-11eb-8743-cbd7253be0f9.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a response prompt in HTML
- [x] Style response and button with CSS
- [x] Have the prompt trigger when the submit button of the practice form is clicked.
- [x] Create a "Correct" prompt that is green, and changes the result container's border to green, and shows a "Next Question" `button`
- [x] Create an "Incorrect" prompt that is red, and changes the result container's border to red (and also shows the next question button."
- [x] Change the border back to blue when the next question is loaded.
- [x] Update `data.practice.userAnswer` with User's inputted answer.
- [x] Create a function that takes each user answer and api response, manipulates each string to sort and eliminate spaces and then compare the strings.
- [x] Show appropriate prompt depending on comparison result along with correct answer if wrong.
- [x] Update form to change problem when the "Next Problem" button is selected instead of when the submit button is selected.
- [x] When 'Next Problem' is selected, reset the `textarea`.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
