### ISSUE TITLE
User can view learning progress.

### ISSUE THREAD

**Issue by alexdenbaugh** [alexdenbaugh/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view learning progress.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can see there progress for each problem type by a comparison of correct answers out of total problems.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature five screen shot mobile](https://user-images.githubusercontent.com/78943990/114768028-3d1f3580-9d1d-11eb-8c02-d3ee74d2d5af.PNG)
![Feature five screen shot desktop](https://user-images.githubusercontent.com/78943990/114768034-3e506280-9d1d-11eb-9635-615bc9017990.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a `data-view=progress`
- [x] Add four divs to represent the four different practice problem types.
- [x] Add rest of HTML
- [x] Style in CSS
- [x] Create 4-5 different color classes depending on % answered correctly.
- [x] Change view swapper to switch the view to progress when "progress" link is clicked in the hamburger menu and the brain icon on the home page is clicked.
- [x] Add a button in progress view that changes the view to the practice settings view.
- [x] Keep track of correct and incorrect answers and save them in data.practice
- [x] After submit button is clicked, save and push data.practice info into the appropriate array in data.progress depending on problem type
- [x] Set up local storage and JSON conversion in data.js.
- [x] Make function that updates DOM of progress view to display the user's progress for each problem type.  
- [x] Change the color of the div depending on % correct.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
